### ISSUE TITLE
Problems to be fixed

### ISSUE THREAD

**Issue by nogov** [Folia412/Labs#1]
1) One-way lost should not have `tail`. It only has `head`.
2) There is no way to enumerate all elements of the list. 
3) Usability of `Amount` method could be better if you passed element to search for as a method argument.
4) Comparison of two lists is implemented incorrectly. Please, fix the algorithm so it compares each elements of both lists.
5) Put each class into its own file.
6) Cover listed fixes with unit tests.

**Comment by Folia412** [comment]
> 1. One-way lost should not have `tail`. It only has `head`.
> 2. There is no way to enumerate all elements of the list.
> 3. Usability of `Amount` method could be better if you passed element to search for as a method argument.
> 4. Comparison of two lists is implemented incorrectly. Please, fix the algorithm so it compares each elements of both lists.
> 5. Put each class into its own file.
> 6. Cover listed fixes with unit tests.

Changes have been made. Could you check?

**Comment by nogov** [comment]
👍
